### PR TITLE
PowAndEmission 

### PR DESCRIPTION
**Pull request by vyasaniket**
It contains info on Last 24 hours POW and emission.
I have used Axios library for making HTTP requests.
I have used Mempool Api (https://mempool.space/api/v1/)
It show data of Next Difficulty Estimated, Difficulty adjust time, Avg block time, Avg block size, blocks count, block reward and  block reward halving

### CODE REVIEW

**Comment by akumalla-s** [comment]
The project setup is not correct. Please see the structure and use tsx instead of js.

**Comment by vyasaniket** [comment]
Have changed to tsx files

**Comment by vyasaniket** [comment]
@dnaiel0809 Can you please review my pr and approve it?

**Review by dnaiel0809 — DISMISSED** [review]
Hi @vyasaniket I did not see any conflicts and errors when I executed your code. However, I am not sure if you want to add your components into the main page. I will approve your PR for now.

**Pull request closed without merging**
