### PR TITLE
 Miner and address statistics with integration tests

### PR DESCRIPTION
**Pull request by rohitpanicker06**
Changes for displaying Miner statistics and address statistics with search functionality. 

Screenshot 2024-03-20 at 2 20 52 PM

Screenshot 2024-03-20 at 3 59 21 PM

### CODE REVIEW

**Review by atharvaneu — APPROVED** [review]
LGTM :+1:

**Comment by anujakale14** [comment]
I've reviewed the changes and everything looks good to me

**Comment by tarunangrish-neu** [comment]
Looks good to go

**Review by kirubagarthiagarajan — APPROVED** [review]
LGTM

**Pull request merged**
