### PR TITLE
Danielnewheart_CountryNodesStats

### PR DESCRIPTION
**Pull request by Danielnewheart**

### CODE REVIEW

**Comment by Danielnewheart** [comment]
@akumalla-s Could you please review it and merge it? I merged my branch right after your branch had been merged. Thank you bro 😉

**Comment by akumalla-s** [comment]
@Danielnewheart I am running the main branch code I don't see any components reflecting on UI including mine. 
image

It's not because of my component add. Even I tried to print Hello in a div it's not reflecting on UI

**Comment by Danielnewheart** [comment]
So does that mean the main branch have some problem?

**Comment by akumalla-s** [comment]
@Danielnewheart Is main branch working in your machine?

**Comment by Danielnewheart** [comment]
No.... But it seems that the error was from other file. Maybe RichListChart.tsx
How about yours?

**Comment by akumalla-s** [comment]
@Danielnewheart the error is not just that one file. All the typescript files JSX has this error.

**Comment by Danielnewheart** [comment]
@akumalla-s I kind of know what happened... I think it's because someone's PR in grafbase repo isn't be merged, but his PR here has been merged. Therefore we cannot run it on our machine because we don't have the required API.

**Comment by Danielnewheart** [comment]
CleanShot 2024-03-19 at 13 38 11

The Blockchairapi hasn't been merged yet. So it's not our wrong and our business... 🫠

**Comment by dnaiel0809** [comment]
Hi @Danielnewheart, I just made a Blockchairapi RP on grafbase repo. Please see if that solves your error.

**Comment by akumalla-s** [comment]
@Danielnewheart Understood, I don't know if I have to hold your PR or approve. Even I approve in anyways you won't see your component UI.

**Comment by Danielnewheart** [comment]
@dnaiel0809 Can you run main branch well on your machine?

**Comment by Danielnewheart** [comment]
@akumalla-s I know... but apparently the problem is on the main branch. I just try to merge it into my branch. So could you please approve my branch so that I don't need to remerge again. And @dnaiel0809 can try to fix the bug.

**Review by akumalla-s — APPROVED** [review]

**Comment by Danielnewheart** [comment]
@akumalla-s Thank you so much, man.

**Comment by Danielnewheart** [comment]
I fixed some bugs about graphQL and Now I believe every UI components can work well.

**Review by akumalla-s — APPROVED** [review]
It looks good from my side as well. I approve. Thanks @Danielnewheart  for fixes

**Pull request merged**
