### PR TITLE
Chore: Set Up SEO Basics in RootLayout with Next.js Head

### PR DESCRIPTION
**Pull request by anujakale14**

### CODE REVIEW

**Comment by anujakale14** [comment]
Hi @Shaiz-Akhtar  can you review this?

**Comment by anujakale14** [comment]
@Anuja-Shinde-02 can you review this?

**Comment by anujakale14** [comment]
@Anuja-Shinde-02 can you review?

**Review by Anuja-Shinde-02 — APPROVED** [review]
Looks fine.

**Pull request merged**
