### PR TITLE
Blocklists component

### PR DESCRIPTION
**Pull request by sushma110396**

### CODE REVIEW

**Comment by sushma110396** [comment]
@RakshitaJ-Neu Can you please review my PR?

**Comment by tarunangrish-neu** [comment]
As discussed over the call, everything looks good. Hence, approving PR.

**Review by tarunangrish-neu — APPROVED** [review]
Looks good to go.

**Comment by RakshitaJ-Neu** [comment]
PR reviewed, looks good as discussed over call.

**Review by RakshitaJ-Neu — APPROVED** [review]

**Pull request merged**
